const SUPABASE_URL="https://embgwbcdiscfnsjsceei.supabase.co";
const SUPABASE_KEY="sb_publishable_wd2Vqxzkb9oi9xy56knx4Q_w21mjTTh";
const db=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY);
let shifts=[],profiles=[],tools=[],productions=[],downtime=[],oee=[],charts={};
const $=id=>document.getElementById(id), num=v=>Number(v||0), esc=s=>String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m])), pct=v=>(num(v)*100).toFixed(1)+"%";
function toast(msg,bad=false){const e=$("toast");e.textContent=msg;e.style.borderColor=bad?"#7f1d1d":"#334155";e.classList.add("show");clearTimeout(window.__toast);window.__toast=setTimeout(()=>e.classList.remove("show"),2600)}
function showError(e,w){console.error(w,e);toast(`${w}: ${e?.message||e}`,true)}
function tab(name){document.querySelectorAll(".tab").forEach(x=>x.classList.add("hidden"));$(name)?.classList.remove("hidden");document.querySelectorAll(".navbtn").forEach(x=>x.classList.toggle("active",x.dataset.tab===name));if($("mobileTab"))$("mobileTab").value=name;if(name==="recovery")renderTrash();if(name==="downtime")renderDowntime();if(name==="dashboard"||name==="machine")requestAnimationFrame(()=>renderCharts())}
document.querySelectorAll(".navbtn").forEach(b=>b.addEventListener("click",()=>tab(b.dataset.tab)));$("mobileTab").addEventListener("change",e=>tab(e.target.value));
const savedTheme=localStorage.getItem("cnc5000-theme");if(savedTheme==="dark")document.documentElement.classList.add("dark");$("theme").textContent=document.documentElement.classList.contains("dark")?"☀":"☾";$("theme").onclick=()=>{document.documentElement.classList.toggle("dark");const dark=document.documentElement.classList.contains("dark");localStorage.setItem("cnc5000-theme",dark?"dark":"light");$("theme").textContent=dark?"☀":"☾";renderCharts()};
async function load(){
 try{$("status").className="status connecting";$('status').innerHTML="<i></i>Connecting";
  const rs=await Promise.all([
   db.from("shifts").select("*").eq("is_deleted",false).order("shift_date",{ascending:false}).limit(1000),
   db.from("cnc_cycle_times").select("*").eq("is_deleted",false).order("profile_code"),
   db.from("cnc_tool_bits").select("*").eq("is_deleted",false).order("category"),
   db.from("production_records").select("*").order("created_at",{ascending:false}).limit(3000),
   db.from("downtime_events").select("*").order("created_at",{ascending:false}).limit(3000),
   db.from("v_shift_oee").select("*").order("shift_date",{ascending:false}).limit(1000)
  ]);for(const r of rs)if(r.error)throw r.error;[shifts,profiles,tools,productions,downtime,oee]=rs.map(r=>r.data||[]);
  $("status").className="status online";$('status').innerHTML="<i></i>Online";renderAll();
 }catch(e){$("status").className="status error";$('status').innerHTML="<i></i>Database error";showError(e,"Supabase")}finally{setTimeout(()=>$("boot").classList.add("hide"),180)}
}
function renderAll(){renderDashboard();renderShifts();renderProduction();renderProfiles();renderTools();renderDowntime();renderMachine();renderTrash();requestAnimationFrame(renderCharts)}
function aggregate(){const total=oee.reduce((s,r)=>s+num(r.total_produced),0),reject=oee.reduce((s,r)=>s+num(r.rejected),0),planned=oee.reduce((s,r)=>s+num(r.planned_minutes),0),operating=oee.reduce((s,r)=>s+num(r.operating_minutes),0),ideal=oee.reduce((s,r)=>s+num(r.ideal_cycle_seconds)*num(r.total_produced),0);const A=planned?Math.min(1,operating/planned):0,Praw=operating?ideal/(operating*60):0,P=Math.min(1,Math.max(0,Praw)),Q=total?Math.max(0,(total-reject)/total):0;return{total,reject,good:Math.max(0,total-reject),planned,operating,A,P,Praw,Q,OEE:A*P*Q,down:oee.reduce((s,r)=>s+num(r.downtime_minutes),0)}}
function renderDashboard(){const a=aggregate();$("kOee").textContent=pct(a.OEE);$("kApq").textContent=`A ${pct(a.A)} · P ${pct(a.P)} · Q ${pct(a.Q)}`;$("kOutput").textContent=a.good.toLocaleString();$("kGood").textContent=`Total ${a.total.toLocaleString()} · Scrap ${a.reject.toLocaleString()}`;$("kShifts").textContent=oee.length;$("kDown").textContent=`${a.down.toFixed(0)}m`;$('kTools').textContent=tools.filter(t=>num(t.stock)<=num(t.min_stock)).length;["A","P","Q"].forEach(k=>{$("bar"+k).textContent=pct(a[k]);$("bar"+k+"Fill").style.width=Math.min(100,num(a[k])*100)+"%"});$("recent").innerHTML=oee.slice(0,8).map(r=>`<tr><td>${esc(r.shift_date)}</td><td>${esc(r.shift_type)}</td><td>${esc(r.team||"-")}</td><td>${num(r.total_produced)}</td><td>${num(r.rejected)}</td><td><b>${pct(r.oee)}</b></td></tr>`).join("")||emptyRow(6,"No shift data yet.")}
function emptyRow(n,msg){return `<tr><td colspan="${n}" class="empty-row">${esc(msg)}</td></tr>`}
function renderShifts(){const q=($("shiftSearch")?.value||"").toLowerCase(),f=$("shiftFilter")?.value||"ALL",from=$("fromDate")?.value||"",to=$("toDate")?.value||"";const rows=oee.filter(r=>(f==="ALL"||r.shift_type===f)&&(!from||r.shift_date>=from)&&(!to||r.shift_date<=to)&&(`${r.shift_date} ${r.team||""} ${r.operator_name||""}`.toLowerCase().includes(q)));$("shiftRows").innerHTML=rows.map(r=>`<tr><td>${esc(r.shift_date)}</td><td>${esc(r.shift_type)}</td><td>${esc(r.team||"-")}</td><td>${num(r.planned_minutes)}m</td><td>${num(r.operating_minutes)}m</td><td>${num(r.total_produced)}</td><td>${num(r.good_parts)}</td><td>${num(r.rejected)}</td><td>${num(r.downtime_minutes)}m</td><td><b>${pct(r.oee)}</b></td><td><button class="action blue" onclick="editShift(${r.id})">Edit</button><button class="action red" onclick="deleteShift(${r.id})">Delete</button></td></tr>`).join("")||emptyRow(11,"No matching shifts.")}
function renderProduction(){const map=new Map(shifts.map(s=>[s.id,s]));const rows=productions.map(p=>{const s=map.get(p.shift_id);return s?`<tr><td>${esc(s.shift_date)}</td><td>${esc(s.shift_type)}</td><td><b>${esc(p.profile_code)}</b></td><td>${num(p.produced)}</td><td>${num(p.rejected)}</td><td>${Math.max(0,num(p.produced)-num(p.rejected))}</td></tr>`:""}).join("");$("prodRows").innerHTML=rows||emptyRow(6,"No production records.");$("prodCount").textContent=productions.length;$("prodTotal").textContent=productions.reduce((s,p)=>s+num(p.produced),0).toLocaleString();$("prodScrap").textContent=productions.reduce((s,p)=>s+num(p.rejected),0).toLocaleString();$("prodGood").textContent=(productions.reduce((s,p)=>s+num(p.produced)-num(p.rejected),0)).toLocaleString()}
function renderDowntime(){const map=new Map(shifts.map(s=>[s.id,s]));$("downRows").innerHTML=downtime.slice(0,120).map(d=>{const s=map.get(d.shift_id);return `<tr><td>${esc(s?.shift_date||"-")}</td><td>${esc(s?.shift_type||"-")}</td><td>${esc(d.reason||"-")}</td><td>${num(d.duration_min)}</td></tr>`}).join("")||emptyRow(4,"No downtime records.")}
function renderProfiles(){const q=($("profileSearch")?.value||"").toLowerCase();const rows=profiles.filter(p=>`${p.profile_code} ${p.description||""}`.toLowerCase().includes(q));$("profileRows").innerHTML=rows.map(p=>`<tr><td><b>${esc(p.profile_code)}</b></td><td>${esc(p.description||"-")}</td><td>${num(p.cycle_seconds)}s</td><td>${esc(p.feed_speeds||"-")}</td><td>${esc(p.tooling||"-")}</td><td><button class="action blue" onclick="editProfile(${p.id})">Edit</button><button class="action red" onclick="deleteProfile(${p.id})">Delete</button></td></tr>`).join("")||emptyRow(6,"No profiles.")}
function renderTools(){const q=($("toolSearch")?.value||"").toLowerCase(),cat=$("toolCat")?.value||"ALL";const rows=tools.filter(t=>(cat==="ALL"||t.category===cat)&&`${t.category} ${t.diameter} ${t.description||""} ${t.location||""}`.toLowerCase().includes(q));$("toolRows").innerHTML=rows.map(t=>{const s=num(t.stock),min=num(t.min_stock),cls=s===0?"danger":s<=min?"" : "green";return `<tr><td><b>${esc(t.category)}</b></td><td>${esc(t.diameter)}</td><td>${esc(t.description||"-")}</td><td><button class="action" onclick="stock(${t.id},-1)">−</button><b class="${cls}">${s}</b><button class="action" onclick="stock(${t.id},1)">＋</button></td><td>${min}</td><td>${esc(t.location||"-")}</td><td><button class="action blue" onclick="editTool(${t.id})">Edit</button><button class="action red" onclick="deleteTool(${t.id})">Dispose</button></td></tr>`}).join("")||emptyRow(7,"No tools.")}
function renderMachine(){const latest=oee[0];if(!latest)return;$("machineShift").textContent=`${latest.shift_date} · ${latest.shift_type}`;$("machineOperating").textContent=`${num(latest.operating_minutes)} min`;$('machineDowntime').textContent=`${num(latest.downtime_minutes)} min`;$("machineProfile").textContent=profiles[0]?.profile_code||"Not assigned";$("machineLast").textContent=`${num(latest.total_produced)} pcs`}
async function renderTrash(){try{const [p,t,s]=await Promise.all([db.from("cnc_cycle_times").select("*").eq("is_deleted",true).order("deleted_at",{ascending:false}),db.from("cnc_tool_bits").select("*").eq("is_deleted",true).order("deleted_at",{ascending:false}),db.from("shifts").select("*").eq("is_deleted",true).order("deleted_at",{ascending:false})]);if(p.error||t.error||s.error)throw p.error||t.error||s.error;$("trashProfiles").innerHTML=(p.data||[]).map(x=>trashCard(x.profile_code,x.id,"profile")).join("")||emptyText();$("trashTools").innerHTML=(t.data||[]).map(x=>trashCard(`${x.category} ${x.diameter}`,x.id,"tool")).join("")||emptyText();$("trashShifts").innerHTML=(s.data||[]).map(x=>trashCard(`${x.shift_date} ${x.shift_type}`,x.id,"shift")).join("")||emptyText()}catch(e){console.warn(e)}}
const emptyText=()=>`<div class="trash-card">Vault empty.</div>`;function trashCard(label,id,type){return `<div class="trash-card"><span>${esc(label)}</span><button class="action green" onclick="restore('${type}',${id})">Restore</button></div>`}
async function ensureScript(src,test){if(test())return;await new Promise((res,rej)=>{const s=document.createElement("script");s.src=src;s.onload=res;s.onerror=()=>rej(new Error("Unable to load report library"));document.head.appendChild(s)})}
async function renderCharts(){try{await ensureScript("https://cdn.jsdelivr.net/npm/chart.js",()=>!!window.Chart);const labels=[...new Set(oee.map(x=>x.shift_date))].sort().slice(-14);const byDate=d=>oee.filter(x=>x.shift_date===d);const oe=labels.map(d=>{const rs=byDate(d),pp=rs.reduce((s,r)=>s+num(r.planned_minutes),0),op=rs.reduce((s,r)=>s+num(r.operating_minutes),0),tp=rs.reduce((s,r)=>s+num(r.total_produced),0),rej=rs.reduce((s,r)=>s+num(r.rejected),0),ic=rs.reduce((s,r)=>s+num(r.ideal_cycle_seconds)*num(r.total_produced),0),A=pp?Math.min(1,op/pp):0,P=op?Math.min(1,ic/(op*60)):0,Q=tp?Math.max(0,(tp-rej)/tp):0;return +(A*P*Q*100).toFixed(1)});const po=labels.map(d=>byDate(d).reduce((s,r)=>s+Math.max(0,num(r.total_produced)-num(r.rejected)),0));const downMap={};downtime.forEach(d=>downMap[d.reason||"Other"]=(downMap[d.reason||"Other"]||0)+num(d.duration_min));const downLabels=Object.keys(downMap).sort((a,b)=>downMap[b]-downMap[a]).slice(0,8),downVals=downLabels.map(x=>downMap[x]);const opts={responsive:true,maintainAspectRatio:false,plugins:{legend:{labels:{color:getComputedStyle(document.documentElement).getPropertyValue("--muted")}}},scales:{x:{ticks:{color:getComputedStyle(document.documentElement).getPropertyValue("--muted")},grid:{color:getComputedStyle(document.documentElement).getPropertyValue("--line")}},y:{ticks:{color:getComputedStyle(document.documentElement).getPropertyValue("--muted")},grid:{color:getComputedStyle(document.documentElement).getPropertyValue("--line")}}}};if(charts.oee)charts.oee.destroy();if(charts.prod)charts.prod.destroy();if(charts.down)charts.down.destroy();charts.oee=new Chart($("oeeChart"),{type:"line",data:{labels,datasets:[{label:"OEE %",data:oe,borderColor:"#3b82f6",backgroundColor:"rgba(59,130,246,.10)",fill:true,tension:.3,pointRadius:3,borderWidth:2}]},options:{...opts,scales:{...opts.scales,y:{...opts.scales.y,beginAtZero:true,max:100}}}});charts.prod=new Chart($("prodChart"),{type:"bar",data:{labels,datasets:[{label:"Good pcs",data:po,backgroundColor:"#10b981",borderRadius:5}]},options:opts});charts.down=new Chart($("downChart"),{type:"bar",data:{labels:downLabels,datasets:[{label:"Minutes",data:downVals,backgroundColor:"#ef4444",borderRadius:5}]},options:{...opts,indexAxis:"y"}});$("oeeEmpty").style.display=labels.length?"none":"grid";$("prodEmpty").style.display=labels.length?"none":"grid";$("downEmpty").style.display=downLabels.length?"none":"grid"}catch(e){console.warn("Chart load",e)}}
function openModal(title,html){$("modalTitle").textContent=title;$("modalBody").innerHTML=`<div class="modal-body">${html}</div>`;$("modal").classList.remove("hidden")};function closeModal(){$("modal").classList.add("hidden")};$("modal").addEventListener("click",e=>{if(e.target.id==="modal")closeModal()});
function formField(label,name,value,type="text",extra=""){return `<label><span class="form-label">${label}</span><input class="input" name="${name}" type="${type}" value="${esc(value)}" ${extra}></label>`}
function openShift(id=null){const s=id?shifts.find(x=>x.id===id):null;openModal(id?"Edit Shift":"Record CNC 5000 Shift",`<form id="shiftForm"><input type="hidden" name="id" value="${s?.id||""}"><div class="form-grid">${formField("Shift date","shift_date",s?.shift_date||new Date().toISOString().slice(0,10),"date","required")}${formField("Shift","shift_type",s?.shift_type||"Day")} ${formField("Team","team",s?.team||"")} ${formField("Operator","operator_name",s?.operator_name||"")} ${formField("Planned minutes","planned_minutes",s?.planned_minutes??630,"number","min=0")}${formField("Break minutes","planned_break_minutes",s?.planned_break_minutes??90,"number","min=0")}${formField("Operating minutes","operating_minutes",s?.operating_minutes??0,"number","min=0")}${formField("Downtime minutes","downtime_minutes",s?.downtime_minutes??0,"number","min=0")}${formField("Total produced","total_produced",s?.total_produced??0,"number","min=0")}${formField("Rejected","rejected",s?.rejected??0,"number","min=0")}${formField("Ideal cycle seconds","ideal_cycle_seconds",s?.ideal_cycle_seconds??0,"number","step=0.01 min=0")}<label class="full"><span class="form-label">Notes</span><textarea class="input" name="notes" rows="3">${esc(s?.notes||"")}</textarea></label></div><div class="modal-actions"><button type="button" class="secondary" onclick="closeModal()">Cancel</button><button class="primary">Save Shift</button></div></form>`);$("shiftForm").onsubmit=saveShift}
async function saveShift(e){e.preventDefault();const x=Object.fromEntries(new FormData(e));const p={shift_date:x.shift_date,shift_type:x.shift_type,team:x.team||null,operator_name:x.operator_name||null,planned_minutes:num(x.planned_minutes)||630,planned_break_minutes:num(x.planned_break_minutes)||90,operating_minutes:num(x.operating_minutes),downtime_minutes:num(x.downtime_minutes),total_produced:Math.trunc(num(x.total_produced)),rejected:Math.trunc(num(x.rejected)),ideal_cycle_seconds:num(x.ideal_cycle_seconds),notes:x.notes||null};if(p.rejected>p.total_produced)return toast("Rejected cannot exceed total produced",true);const r=x.id?await db.from("shifts").update(p).eq("id",x.id):await db.from("shifts").insert(p);if(r.error)return showError(r.error,"Save shift");toast("Shift saved");closeModal();load()}
function editShift(id){openShift(id)}
function openProfile(id=null){const p=id?profiles.find(x=>x.id===id):null;openModal(id?"Edit CNC Profile":"Add CNC Profile",`<form id="profileForm"><input type="hidden" name="id" value="${p?.id||""}"><div class="form-grid">${formField("Profile code","profile_code",p?.profile_code||"")} ${formField("Description","description",p?.description||"")} ${formField("Length","length",p?.length||"")} ${formField("Cycle seconds","cycle_seconds",p?.cycle_seconds??0,"number","min=0 step=.01")} ${formField("Feed / speed","feed_speeds",p?.feed_speeds||"")} ${formField("Tooling","tooling",p?.tooling||"")}<label class="full"><span class="form-label">Notes</span><textarea class="input" name="notes" rows="3">${esc(p?.notes||"")}</textarea></label></div><div class="modal-actions"><button type="button" class="secondary" onclick="closeModal()">Cancel</button><button class="primary">Save Profile</button></div></form>`);$("profileForm").onsubmit=async e=>{e.preventDefault();const x=Object.fromEntries(new FormData(e)),pld={profile_code:x.profile_code.trim(),description:x.description||null,length:x.length||null,cycle_seconds:num(x.cycle_seconds),feed_speeds:x.feed_speeds||null,tooling:x.tooling||null,notes:x.notes||null},r=x.id?await db.from("cnc_cycle_times").update(pld).eq("id",x.id):await db.from("cnc_cycle_times").insert(pld);if(r.error)return showError(r.error,"Save profile");toast("Profile saved");closeModal();load()}}
function editProfile(id){openProfile(id)}
function openTool(id=null){const t=id?tools.find(x=>x.id===id):null;openModal(id?"Edit Tool":"Add Tool",`<form id="toolForm"><input type="hidden" name="id" value="${t?.id||""}"><div class="form-grid">${formField("Category","category",t?.category||"End Mill")} ${formField("Diameter / Size","diameter",t?.diameter||"")} ${formField("Description","description",t?.description||"")} ${formField("Stock","stock",t?.stock??0,"number","min=0")} ${formField("Minimum stock","min_stock",t?.min_stock??2,"number","min=0")} ${formField("Location","location",t?.location||"Main Storage Rack")}</div><div class="modal-actions"><button type="button" class="secondary" onclick="closeModal()">Cancel</button><button class="primary">Save Tool</button></div></form>`);$("toolForm").onsubmit=async e=>{e.preventDefault();const x=Object.fromEntries(new FormData(e)),pld={category:x.category,diameter:x.diameter.trim(),description:x.description||null,stock:Math.max(0,Math.trunc(num(x.stock))),min_stock:Math.max(0,Math.trunc(num(x.min_stock))),location:x.location||"Main Storage Rack"},r=x.id?await db.from("cnc_tool_bits").update(pld).eq("id",x.id):await db.from("cnc_tool_bits").insert(pld);if(r.error)return showError(r.error,"Save tool");toast("Tool saved");closeModal();load()}}
function editTool(id){openTool(id)}
async function stock(id,delta){const t=tools.find(x=>x.id===id);if(!t)return;const n=Math.max(0,num(t.stock)+delta),r=await db.from("cnc_tool_bits").update({stock:n}).eq("id",id);if(r.error)return showError(r.error,"Stock update");toast("Stock updated");load()}
async function deleteTool(id){if(!confirm("Move this tool to Recovery?"))return;const r=await db.from("cnc_tool_bits").update({is_deleted:true,deleted_at:new Date().toISOString()}).eq("id",id);if(r.error)return showError(r.error,"Dispose tool");toast("Tool moved to Recovery");load()}
async function deleteProfile(id){if(!confirm("Move this profile to Recovery?"))return;const r=await db.from("cnc_cycle_times").update({is_deleted:true,deleted_at:new Date().toISOString()}).eq("id",id);if(r.error)return showError(r.error,"Delete profile");toast("Profile moved to Recovery");load()}
async function deleteShift(id){if(!confirm("Move this shift to Recovery? Production and downtime remain linked."))return;const r=await db.from("shifts").update({is_deleted:true,deleted_at:new Date().toISOString()}).eq("id",id);if(r.error)return showError(r.error,"Delete shift");toast("Shift moved to Recovery");load()}
async function restore(type,id){const table=type==="profile"?"cnc_cycle_times":type==="tool"?"cnc_tool_bits":"shifts",r=await db.from(table).update({is_deleted:false,deleted_at:null}).eq("id",id);if(r.error)return showError(r.error,"Restore");toast("Restored");load()}
async function createRequisition(){const low=tools.filter(t=>num(t.stock)<=num(t.min_stock));if(!low.length)return toast("No tools are at or below minimum stock.");openModal("Restock Requisition",`<div class="stack">${low.map(t=>`<div class="trash-card"><span><b>${esc(t.category)}</b> · ${esc(t.diameter)} · Stock ${num(t.stock)}</span><b class="danger">Order 5</b></div>`).join("")}</div><div class="modal-actions"><button id="saveReq" class="primary">Submit Requisition</button></div>`);$("saveReq").onclick=async()=>{const h=await db.from("tool_requisitions").insert({requested_by:"CNC 5000 Operations",supervisor:"Mr. U.N. Kavinda",status:"Submitted"}).select().single();if(h.error)return showError(h.error,"Requisition");const items=low.map(t=>({requisition_id:h.data.id,tool_id:t.id,category:t.category,diameter:t.diameter,stock_at_request:t.stock,requested_qty:5,priority:num(t.stock)===0?"Critical":"Urgent"}));const r=await db.from("tool_requisition_items").insert(items);if(r.error)return showError(r.error,"Requisition items");toast("Restock requisition submitted");closeModal()}}
async function exportExcel(){try{await ensureScript("https://cdn.jsdelivr.net/npm/xlsx@0.18.5/dist/xlsx.full.min.js",()=>!!window.XLSX);const rows=oee.map(r=>({Date:r.shift_date,Shift:r.shift_type,Team:r.team||"",Planned_Min:r.planned_minutes,Operating_Min:r.operating_minutes,Produced:r.total_produced,Good:r.good_parts,Reject:r.rejected,Downtime_Min:r.downtime_minutes,Availability:pct(r.availability),Performance:pct(Math.min(1,num(r.performance_raw))),Quality:pct(r.quality),OEE:pct(r.oee)}));const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(rows),"Shift_OEE");XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(profiles),"Profiles");XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(tools),"Tools");XLSX.writeFile(wb,`CNC5000_Report_${new Date().toISOString().slice(0,10)}.xlsx`)}catch(e){showError(e,"Excel export")}}
async function exportPDF(){try{await ensureScript("https://cdnjs.cloudflare.com/ajax/libs/jspdf/2.5.1/jspdf.umd.min.js",()=>!!window.jspdf);await ensureScript("https://cdnjs.cloudflare.com/ajax/libs/jspdf-autotable/3.5.31/jspdf.plugin.autotable.min.js",()=>!!window.jspdf?.jsPDF?.API?.autoTable);const {jsPDF}=window.jspdf,doc=new jsPDF("p","mm","a4");doc.setFontSize(16);doc.text("ALUMEX PLC - CNC 5000 OPERATIONS REPORT",14,16);doc.setFontSize(9);doc.text(`Generated ${new Date().toLocaleString()}`,14,23);const rows=oee.slice(0,80).map(r=>[r.shift_date,r.shift_type,r.team||"-",r.total_produced,r.good_parts,r.rejected,`${num(r.downtime_minutes)}m`,pct(r.oee)]);doc.autoTable({head:[["Date","Shift","Team","Produced","Good","Scrap","Down","OEE"]],body:rows,startY:30,styles:{fontSize:7},headStyles:{fillColor:[37,99,235]}});doc.save(`CNC5000_Report_${new Date().toISOString().slice(0,10)}.pdf`)}catch(e){showError(e,"PDF export")}}
function printReport(){window.print()}
window.addEventListener("load",load);
